version: '3.8'
services:
    postgres:
        build:
            context: ./postgres
            #network: app_net
        container_name: postgres
        networks:
            app_net:
              ipv4_address: 172.18.0.2
        ports:
            - "5432:5432"
    proxy:
        build:
            context: ./nginx
            #network: app_net
        container_name: proxy
        networks:
            app_net:
                ipv4_address: 172.18.0.3
        ports:
            - "81:80"
        links:
            - login_service
    login_service:
        build:
            context: ./backend/loginService
        container_name: login_service
        networks:
            app_net:
                ipv4_address: 172.18.0.4
        ports:
            - "5001:5000"
networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
        external: false
        name: app_net